### ISSUE TITLE
When the VRCFury componate to be converted is in a prefab and is referenced by a number of costume prefabs starting from the elementary prefab that holds it, the build fails if you try to execute it in the MA -> VRCFury execution order.

### ISSUE THREAD

**Issue by ni1chigo2115** [hai-vr/modular-fury-please-behave#1]
When the VRCFury componate to be converted is in a prefab and is referenced by a number of costume prefabs starting from the elementary prefab that holds it, the build fails if you try to execute it in the MA -> VRCFury execution order.

It's hard to explain, but it seems that if I have an avatar prefab with a costume that references a prefab holding a VRCFury componate, if I try to run it in the MA -> VRCFury execution order, it fails to NDMF or build.

**Comment by ni1chigo2115** [comment]
Also, when doing this conversion process, if a large number of avatars are referencing an elementary prefab with VRCFury compornents, it will try to convert all prefabs as NDMFs, which will increase build time.

**Comment by hai-vr** [comment]
Thank you for the issue report. I am no longer maintaining this project because [VRCFury now has internal handling for NDMF](https://github.com/VRCFury/VRCFury/commit/cea3d207626e28e25dc652a7acd851462928c576) starting from v1.648.0.
